### ISSUE TITLE
Feedback: Dictionary format for v anandajyoti

### ISSUE THREAD

**Issue by parthopdas** [digitalpalitools/enhanced-digital-pali-dictionary#10]
AC
- [x] Generate output in GD and v anandajyoti formats

Today's feedback from bhante. i think we can start prioritising feedback from this point onwards.

> This is great, and much merit for developing it. 

- [x] P0. DPD should not contain all words, as the data is not checked.  There are two possible solutions. 

1. exclude all words without {Meaning IN CONTEXT}
2. include all words, but if there is no English meaning in context, then same brief info as cdpd i.e. pāli1, grammar and buddhadats

> I think a text inflection table would be really useful.

> Antonym is displaying as ant. instead of ant:
- [x] ant:

**Comment by bdhrs** [comment]
{Pāli1}, {Grammar}, {Neg}, {Verb}, {Trans}, {Case}, {Meaning IN CONTEXT}, lit. {Literal Meaning}, {Pāli Root}{V}{Grp} {Sgn} ({Root Meaning}), {Root In Comps} in comps, base {Base}, constr. {Construction}, {Compound} ({Compound Construction}), ant. {Antonyms}, syn. {Synonyms – different word}, var. {Variant – same constr or diff reading}, cmty. {Commentary}, note. {Notes}, {Sanskrit}, {Sk Root} cl. {Cl}

**Comment by bdhrs** [comment]
if any of those columns are blank, then that column and any preceding text and punctuation should not display. 
i foresee one issue where \n line breaks should be replaced with `, ` comma space.

**Comment by bdhrs** [comment]
feedback from bhante

> I had to modify the .txt file in a few ways, nothing serious, but remove html tags, as I am reading plain text; I also noticed the file was UTF-8, and I had to change that to UTF-8 BOM to read it correctly. 

- [x] UTF-8 BOM format
- [x] remove html tags `<b>` and in future  `<i>`

> Because of the size of the file it doesn't work so good for instant look up, so I now have reverted to the much smaller CPED for instant, and then if I need more info I can search through DPD. Perhaps we could think of exporting a 2nd file (as well as this one) with more basic info for the instant look up? 

- [x] create CDPD (concise DPD) with just the following info.
{Pāli1}; {Grammar}, {Case}; {Meaning IN CONTEXT}

> √gṛdhcl, √garjcl, √gaicl at the end of the entries. What is this cl? Another is √kāṅkṣcl, √kaṣcl, √akṣcl etc. They evidently have significance, but what?

- [x] add space between {Sk Root} cl. {Cl}

- [x] Double check all the other formatting

{Pāli1}; {Grammar}, {Neg}, {Verb}, {Trans}, {Case}; {Meaning IN CONTEXT}, lit. {Literal Meaning}; root: {Pāli Root}{V}{Grp} {Sgn} ({Root Meaning}), {Root In Comps} in comps; base: {Base}; constr: {Construction}; {Compound} ({Compound Construction}), ant: {Antonyms}; syn: {Synonyms – different word}; var: {Variant – same constr or diff reading}; ct: {Commentary}; note: {Notes}; sk: {Sanskrit}, {Sk Root} cl. {Cl}

- [x] space between {Grp} {Sgn}
- [x] root: ant: syn: var: ct: note: sk:
- [x] don't display field if {Root In Comps} = 0

> Apart from that it is really a useful dictionary and addition, and contains some better info that others I have seen, and in a clearer way also, so it is much to be commended.

Here is a screenshot. 

![image](https://user-images.githubusercontent.com/64521731/116031045-886d0880-a67a-11eb-85af-2354c6be4429.png)

**Comment by bdhrs** [comment]
Today's feedback from bhante. i think we can start prioritising feedback from this point onwards.

> This is great, and much merit for developing it. 

> One problem I saw in CDPD we have uttaraṇa (don't know why this became such a sticker), but not in DPD, which probably means the other ones are not there also. I just checked mahāsāla (which I had seen was missing from the earlier version) and now it is missing in both, but is a very common word.

- [ ] P0. CDPD should contain all words. Where there is no {Meaning IN CONTEXT} then substitute with {Buddhadatta}. like on the /inflect webpage.

> I think a text inflection table would be really useful.

- [ ] P1. create a text only version of the inflection tables for DPD. syntax is singular, singular; plural, plural. e.g.
buddho; buddhā, buddhāse. buddhaṃ; buddhe. buddhena; buddhebhi, buddhehi. buddhassa, buddhāya; buddhānaṃ. buddhato, buddhamhā, buddhasmā, buddhā; buddhato, buddhebhi, buddhehi. buddhassa; buddhānaṃ. buddhamhi, buddhasmiṃ, buddhe; buddhesu. buddha, buddhā; buddhā.
