### ISSUE TITLE
P1 Fold away the inflection tables with + sign

### ISSUE THREAD

**Issue by bdhrs** [digitalpalitools/enhanced-digital-pali-dictionary#19]
In GoldenDict there is the option to hide information with a +

- [ ] Have the option to hide the inflection table section by clicking +
default settings is it shows.

![2021-05-02_18-17](https://user-images.githubusercontent.com/64521731/116813694-afdc3d80-ab72-11eb-8394-9c1bfd0d94b2.png)

**Comment by smkvr98** [comment]
update: 
![image](https://user-images.githubusercontent.com/60284375/126033980-69f44398-0263-4eb7-a73f-d2b4be3bcc86.png)
![image](https://user-images.githubusercontent.com/60284375/126034029-15846d53-1001-434b-8251-9496b8a1e923.png)

functionality achieved with details html tag.  '+' sign drop discussed with ven. @bdhrs.

**Comment by bdhrs** [comment]
elegant solution. works well.
