### ISSUE TITLE
P0 Dictionary displaying wrong results

### ISSUE THREAD

**Issue by bdhrs** [digitalpalitools/enhanced-digital-pali-dictionary#20]
These are examples of a class of mistakes that are occurring.

When searching for an inflected form in the dict, it finds an unrelated word, which does not have that inflection in its table. 

Most likely culprit is the syn file, but it could be something else.

gāthāyo finds gātha 
nisīdatu finds nisīdanta
seyyo finds seyyā
seyyo finds seti
seyya finds senta
missaṃ finds mi

https://user-images.githubusercontent.com/64521731/117228603-fa8ddc00-ae36-11eb-8bc1-b99dfa7d1a8d.mp4

**Comment by bdhrs** [comment]
problem is defintely not the .syn file, checked the generated output carefully.

**Comment by parthopdas** [comment]
ok then the only remaining possibilities are (a) goldendict (b) data

**Comment by bdhrs** [comment]
this text file output of the .syn file which sumukha gave me also
eliminates data as the source of the problem. investigating goldendict.

**Comment by smkvr98** [comment]
![image](https://user-images.githubusercontent.com/60284375/120321565-1931a680-c301-11eb-8289-34b9e7482330.png)
Temporary fix.

Relevant Links: 
https://github.com/goldendict/goldendict/issues/198
  and 
http://goldendict.org/forum/viewtopic.php?f=6&t=2120

**Comment by bdhrs** [comment]
yes! that works for me. well found ; )

there is one minor implication of that fix. the tiny handful of users who are working with multiple dictionaries in goldendict can no longer use dpd to find declensions of pāli words in other dictionaries. for example with it on, search for dhammaṃ find dhamma in pts dict, with it off, only dpd results. having said that the problem is not on our side, its a known issue with goldendict, and without making changes to the goldendict, cannot be perfectly solved. 

i am happy to close if there are no objections.
