### ISSUE TITLE
P0 wrong grammtical info displaying 

### ISSUE THREAD

**Issue by bdhrs** [digitalpalitools/enhanced-digital-pali-dictionary#22]
user feedback
the correct grammatical info is displaying in the short heading at the top, but wrong grammatical information is displaying in the detailed information below. they must both match.
![image](https://user-images.githubusercontent.com/64521731/120056249-8838a200-c058-11eb-971e-175f68e27ebd.png)
![image](https://user-images.githubusercontent.com/64521731/120056253-8bcc2900-c058-11eb-815e-edc88531b968.png)

**Comment by bdhrs** [comment]
problem in data not code

**Comment by bdhrs** [comment]
made a test to ensure data integrity in the future

**Comment by smkvr98** [comment]
row of samatta 2 in the csv used for dict generation had inconsistent pos (nt) and grammar (adj) resulting in the above.
