### ISSUE TITLE
P1 Update to AjDict Vocab DPD

### ISSUE THREAD

**Issue by bdhrs** [digitalpalitools/enhanced-digital-pali-dictionary#31]
A request from Ven. Anadajoti to please include all Sanskrit info in the AjDict Full CDPD for a project he is currently working on.

This can be appended onto the end of the text of each entry

sk: `{Sanskrit}`, `{Sk Root}` `{Cl}` `({Sk Root Mn})`

----------------------------------------------------------------------------

Dear Venerable,

I wonder if I could get an update, but one with a change, so that (C)DPD includes whatever info you have on Sanskrit also please, for a project I am working on.

Really appreciate it.

Metta, Anandajoti

**Comment by smkvr98** [comment]
Update: 

Changes only to DPD. CDPD format stays the same.

---

Email from Ven. Aj:

> Actually I think the best thing is, give me the normal stripped down version for the Concise file (otherwise it will slow it down too much), and include the Sanskrit in the main DPD.

**Comment by bdhrs** [comment]
pls add the new fields as well
; ph `{Phonetic Changes}`
; wiki `{Link}`
