### ISSUE TITLE
Feedbacks from DPS

### ISSUE THREAD

**Issue by Devamitta** [digitalpalitools/enhanced-digital-pali-dictionary#7]
The current logic of displaying "grammar" is - if column "grammar" have somthing it is displayed. Since "grammar" in golden dic have many columns from ods (like POS, derived from, etc.) If it is possible, to change the logic of displaying "grammar" to - if column "POS" have somthing.

**Comment by Devamitta** [comment]
Columns "Notes" and "Variant reading" does not display

**Comment by Devamitta** [comment]
If it is possible, to add before column "Derived from" the word "from" if there is somthing in this column.
![1](https://user-images.githubusercontent.com/39419221/114352146-25af4380-9b89-11eb-974d-3d236b8a30e3.jpg)

**Comment by Devamitta** [comment]
Please, attach the link for feedback, same way as in DPD. Just link is different:
https://docs.google.com/forms/d/e/1FAIpQLSc87oKqninpyg01YWdsjdYK6wSeIMoAZpy2jNM7Wu0KYygnHw/viewform?vc=0&c=0&w=1&flr=0

**Comment by parthopdas** [comment]
v @Devamitta closing this as all issues appear to be fixed. please open a new issue with additional feedback.
